#!/bin/bash

# System Info Script Assignment (Week 05)
# By Lucas Shering
# Linux Automation
# Date: June 5, 2026
# Due Date: June 10, 2026
# This is a script that checks certain aspects of the system it's running on, stores the values into variables, and displays the results for the user

# Variable creation for initial information line

hostname=$(hostname)

username=$(whoami)

dateTime=$(date)

# Variable creation for System Information section

source /etc/os-release
os="$PRETTY_NAME"

uptime=$(uptime -p)

cpu=$(lscpu 2>/dev/null | awk -F: '/Model name/ {print $2}' | xargs)

ram=$(lsmem 2>/dev/null | awk '/Total online/ {print $4}')

disks=$(sudo lshw -class disk 2>/dev/null | awk -F: '/product/ {product=$2}/size:/ {size=$2; print product " -" size}' | paste -sd "," -)

video=$(sudo lshw -class video 2>/dev/null | awk -F: '/product/ {model=$2}/vendor/ {make=$2; print make " -" model}')
if [ "$video" = "" ];
	then
        video=" Not detected"
fi

hostInt=$(ip r | awk '/default/ {print $5}')

hostAddr=$(ip a show "$hostInt" 2>/dev/null | awk '/inet/ {print $2; exit}')

gateway=$(ip r | awk '/default/ {print $3}')

dnsServer=$(resolvectl dns "$hostInt" 2>/dev/null | awk '{print $NF}')

# Variable creation for System Status section

users=$(who | awk '{print $1}' | sort -u | paste -sd "," -)
if [ "$users" = "" ];
	then
    	users=$(whoami)
fi

diskSpace=$(df -h | awk '$1 ~ "^/dev/" && $1 !~ "^/dev/sr" {print $6, $4}' | paste -sd "," -)

processes=$(ps -e --no-headers | wc -l)

loadAverages=$(uptime | awk -F'load average: ' '{print $2}')

listeningPorts=$(ss -tuln | awk '$1 != "Netid" {print $5}' | awk -F: '{print $NF}' | sort -n -u | paste -sd "," -)

ufwStatus=$(sudo ufw status 2>/dev/null | awk 'NR==1 {print $2}')

# Report display begins here

cat <<EOF

System report for $hostname generated by $username, on $dateTime

System Information
------------------
OS:  $os
Uptime:  $uptime
CPU:  $cpu
RAM:  $ram
Disk(s): $disks
Video: $video
Host Address:  $hostAddr
Gateway IP:  $gateway
DNS Server:  $dnsServer

System Status
-------------
Users Logged In:  $users
Disk Space:  $diskSpace
Process Count:  $processes
Load Averages:  $loadAverages
Listening Network Ports:  $listeningPorts
UFW Status:  $ufwStatus

EOF
